namespace Gorilla_Mod_Manager
{
    partial class MainApp
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
                components.Dispose();
            base.Dispose(disposing);
        }

        private void InitializeComponent()
        {
            components = new System.ComponentModel.Container();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges25 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges26 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges23 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges24 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges21 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges22 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges19 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges20 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges17 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges18 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges29 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges28 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges15 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges16 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges13 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges14 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges27 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges11 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges12 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges9 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges10 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges7 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges8 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges5 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges6 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges3 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges4 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges1 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            Guna.UI2.WinForms.Suite.CustomizableEdges customizableEdges2 = new Guna.UI2.WinForms.Suite.CustomizableEdges();
            System.ComponentModel.ComponentResourceManager resources = new System.ComponentModel.ComponentResourceManager(typeof(MainApp));

            guna2BorderlessForm1 = new Guna.UI2.WinForms.Guna2BorderlessForm(components);
            guna2AnimateWindow1 = new Guna.UI2.WinForms.Guna2AnimateWindow(components);
            gorillamodmanager = new System.Windows.Forms.Label();
            undertext = new System.Windows.Forms.Label();
            FilePath = new Guna.UI2.WinForms.Guna2TextBox();
            opengamepath = new Guna.UI2.WinForms.Guna2Button();
            DashboardBtn = new Guna.UI2.WinForms.Guna2Button();
            SearchBox = new Guna.UI2.WinForms.Guna2TextBox();
            FilterDropdown = new Guna.UI2.WinForms.Guna2ComboBox();
            Close = new Guna.UI2.WinForms.Guna2CircleButton();
            Minimize = new Guna.UI2.WinForms.Guna2CircleButton();
            guna2Separator1 = new Guna.UI2.WinForms.Guna2Separator();
            ModView = new Guna.UI2.WinForms.Guna2Panel();
            InstallBepinex = new Guna.UI2.WinForms.Guna2Button();
            Github = new Guna.UI2.WinForms.Guna2CircleButton();
            BrowseTabBtn = new Guna.UI2.WinForms.Guna2Button();
            InstalledTabBtn = new Guna.UI2.WinForms.Guna2Button();
            InstalledView = new Guna.UI2.WinForms.Guna2Panel();
            SettingsView = new Guna.UI2.WinForms.Guna2Panel();
            LaunchGameBtn = new Guna.UI2.WinForms.Guna2Button();
            SettingsTabBtn = new Guna.UI2.WinForms.Guna2Button();
            SuspendLayout();

            guna2BorderlessForm1.AnimateWindow = true;
            guna2BorderlessForm1.BorderRadius = 5;
            guna2BorderlessForm1.ContainerControl = this;
            guna2BorderlessForm1.DockIndicatorTransparencyValue = 0.6D;
            guna2BorderlessForm1.DragStartTransparencyValue = 0.7D;
            guna2BorderlessForm1.TransparentWhileDrag = true;

            gorillamodmanager.AutoSize = true;
            gorillamodmanager.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            gorillamodmanager.Font = new System.Drawing.Font("Poppins", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            gorillamodmanager.ForeColor = System.Drawing.Color.White;
            gorillamodmanager.Location = new System.Drawing.Point(131, 15);
            gorillamodmanager.Name = "gorillamodmanager";
            gorillamodmanager.Size = new System.Drawing.Size(240, 37);
            gorillamodmanager.TabIndex = 0;
            gorillamodmanager.Text = "gorilla mod manager";

            undertext.AutoSize = true;
            undertext.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            undertext.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            undertext.ForeColor = System.Drawing.Color.White;
            undertext.Location = new System.Drawing.Point(134, 52);
            undertext.Name = "undertext";
            undertext.Size = new System.Drawing.Size(199, 19);
            undertext.TabIndex = 4;
            undertext.Text = "inspired by monkey mod manager.";

            FilePath.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            FilePath.Animated = true;
            FilePath.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            FilePath.BorderRadius = 4;
            FilePath.Cursor = System.Windows.Forms.Cursors.IBeam;
            FilePath.CustomizableEdges = customizableEdges25;
            FilePath.DefaultText = "";
            FilePath.DisabledState.BorderColor = System.Drawing.Color.FromArgb(208, 208, 208);
            FilePath.DisabledState.FillColor = System.Drawing.Color.FromArgb(226, 226, 226);
            FilePath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(138, 138, 138);
            FilePath.DisabledState.PlaceholderForeColor = System.Drawing.Color.FromArgb(138, 138, 138);
            FilePath.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            FilePath.FocusedState.BorderColor = System.Drawing.Color.FromArgb(94, 148, 255);
            FilePath.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            FilePath.HoverState.BorderColor = System.Drawing.Color.FromArgb(94, 148, 255);
            FilePath.Location = new System.Drawing.Point(136, 85);
            FilePath.Name = "FilePath";
            FilePath.Padding = new System.Windows.Forms.Padding(0, 3, 0, 0);
            FilePath.PlaceholderText = "";
            FilePath.SelectedText = "";
            FilePath.ShadowDecoration.CustomizableEdges = customizableEdges26;
            FilePath.Size = new System.Drawing.Size(318, 30);
            FilePath.TabIndex = 2;

            opengamepath.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            opengamepath.Animated = true;
            opengamepath.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            opengamepath.BorderRadius = 4;
            opengamepath.CustomizableEdges = customizableEdges23;
            opengamepath.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            opengamepath.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            opengamepath.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            opengamepath.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            opengamepath.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            opengamepath.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            opengamepath.ForeColor = System.Drawing.Color.White;
            opengamepath.HoverState.BorderColor = System.Drawing.Color.FromArgb(35, 35, 35);
            opengamepath.HoverState.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            opengamepath.Location = new System.Drawing.Point(462, 85);
            opengamepath.Name = "opengamepath";
            opengamepath.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            opengamepath.ShadowDecoration.CustomizableEdges = customizableEdges24;
            opengamepath.Size = new System.Drawing.Size(43, 30);
            opengamepath.TabIndex = 8;
            opengamepath.Text = "...";
            opengamepath.Click += opengamepath_Click;

            DashboardBtn.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            DashboardBtn.Animated = true;
            DashboardBtn.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            DashboardBtn.BorderRadius = 4;
            DashboardBtn.CustomizableEdges = customizableEdges21;
            DashboardBtn.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            DashboardBtn.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            DashboardBtn.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            DashboardBtn.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            DashboardBtn.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            DashboardBtn.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            DashboardBtn.ForeColor = System.Drawing.Color.White;
            DashboardBtn.HoverState.BorderColor = System.Drawing.Color.FromArgb(111, 69, 240);
            DashboardBtn.HoverState.FillColor = System.Drawing.Color.FromArgb(80, 45, 170);
            DashboardBtn.Location = new System.Drawing.Point(512, 85);
            DashboardBtn.Name = "DashboardBtn";
            DashboardBtn.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            DashboardBtn.ShadowDecoration.CustomizableEdges = customizableEdges22;
            DashboardBtn.Size = new System.Drawing.Size(104, 30);
            DashboardBtn.TabIndex = 9;
            DashboardBtn.Text = "Dashboard";
            DashboardBtn.Click += DashboardBtn_Click;

            SearchBox.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            SearchBox.Animated = true;
            SearchBox.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            SearchBox.BorderRadius = 4;
            SearchBox.Cursor = System.Windows.Forms.Cursors.IBeam;
            SearchBox.CustomizableEdges = customizableEdges19;
            SearchBox.DefaultText = "";
            SearchBox.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            SearchBox.FocusedState.BorderColor = System.Drawing.Color.FromArgb(94, 148, 255);
            SearchBox.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            SearchBox.ForeColor = System.Drawing.Color.White;
            SearchBox.HoverState.BorderColor = System.Drawing.Color.FromArgb(94, 148, 255);
            SearchBox.Location = new System.Drawing.Point(136, 124);
            SearchBox.Name = "SearchBox";
            SearchBox.Padding = new System.Windows.Forms.Padding(0, 3, 0, 0);
            SearchBox.PlaceholderText = "Search mods...";
            SearchBox.SelectedText = "";
            SearchBox.ShadowDecoration.CustomizableEdges = customizableEdges20;
            SearchBox.Size = new System.Drawing.Size(318, 28);
            SearchBox.TabIndex = 10;
            SearchBox.TextChanged += SearchBox_TextChanged;

            FilterDropdown.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            FilterDropdown.BackColor = System.Drawing.Color.FromArgb(21, 21, 21);
            FilterDropdown.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            FilterDropdown.BorderRadius = 5;
            FilterDropdown.CustomizableEdges = customizableEdges17;
            FilterDropdown.DrawMode = System.Windows.Forms.DrawMode.OwnerDrawFixed;
            FilterDropdown.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            FilterDropdown.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            FilterDropdown.FocusedColor = System.Drawing.Color.FromArgb(94, 148, 255);
            FilterDropdown.FocusedState.BorderColor = System.Drawing.Color.FromArgb(94, 148, 255);
            FilterDropdown.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            FilterDropdown.ForeColor = System.Drawing.Color.White;
            FilterDropdown.ItemHeight = 30;
            FilterDropdown.Items.AddRange(new object[] { "All", "Featured", "Verified", "Unverified" });
            FilterDropdown.Location = new System.Drawing.Point(623, 85);
            FilterDropdown.Name = "FilterDropdown";
            FilterDropdown.ShadowDecoration.CustomizableEdges = customizableEdges18;
            FilterDropdown.Size = new System.Drawing.Size(153, 36);
            FilterDropdown.TabIndex = 11;
            FilterDropdown.SelectedIndexChanged += FilterDropdown_SelectedIndexChanged;

            Close.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            Close.Animated = true;
            Close.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            Close.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            Close.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            Close.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            Close.FillColor = System.Drawing.Color.FromArgb(255, 80, 80);
            Close.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            Close.ForeColor = System.Drawing.Color.White;
            Close.Location = new System.Drawing.Point(776, 14);
            Close.Name = "Close";
            Close.ShadowDecoration.CustomizableEdges = customizableEdges29;
            Close.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            Close.Size = new System.Drawing.Size(23, 23);
            Close.TabIndex = 5;
            Close.Click += Close_Click;

            Minimize.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            Minimize.Animated = true;
            Minimize.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            Minimize.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            Minimize.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            Minimize.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            Minimize.FillColor = System.Drawing.Color.FromArgb(255, 162, 80);
            Minimize.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            Minimize.ForeColor = System.Drawing.Color.White;
            Minimize.Location = new System.Drawing.Point(746, 14);
            Minimize.Name = "Minimize";
            Minimize.ShadowDecoration.CustomizableEdges = customizableEdges28;
            Minimize.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            Minimize.Size = new System.Drawing.Size(23, 23);
            Minimize.TabIndex = 6;
            Minimize.Click += Minimize_Click;

            guna2Separator1.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            guna2Separator1.FillColor = System.Drawing.Color.FromArgb(33, 33, 33);
            guna2Separator1.Location = new System.Drawing.Point(136, 159);
            guna2Separator1.Name = "guna2Separator1";
            guna2Separator1.Size = new System.Drawing.Size(690, 12);
            guna2Separator1.TabIndex = 12;

            ModView.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            ModView.BackColor = System.Drawing.Color.FromArgb(33, 33, 33);
            ModView.BorderRadius = 5;
            ModView.CustomizableEdges = customizableEdges15;
            ModView.Location = new System.Drawing.Point(136, 175);
            ModView.Name = "ModView";
            ModView.ShadowDecoration.CustomizableEdges = customizableEdges16;
            ModView.Size = new System.Drawing.Size(716, 335);
            ModView.TabIndex = 13;
            ModView.Paint += ModView_Paint;

            InstallBepinex.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            InstallBepinex.Animated = true;
            InstallBepinex.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            InstallBepinex.BorderRadius = 4;
            InstallBepinex.CustomizableEdges = customizableEdges13;
            InstallBepinex.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            InstallBepinex.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            InstallBepinex.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            InstallBepinex.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            InstallBepinex.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            InstallBepinex.Font = new System.Drawing.Font("Microsoft Sans Serif", 7.5F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            InstallBepinex.ForeColor = System.Drawing.Color.White;
            InstallBepinex.HoverState.BorderColor = System.Drawing.Color.FromArgb(35, 35, 35);
            InstallBepinex.HoverState.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            InstallBepinex.Image = Properties.Resources._39589027;
            InstallBepinex.Location = new System.Drawing.Point(462, 122);
            InstallBepinex.Name = "InstallBepinex";
            InstallBepinex.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            InstallBepinex.ShadowDecoration.CustomizableEdges = customizableEdges14;
            InstallBepinex.Size = new System.Drawing.Size(43, 30);
            InstallBepinex.TabIndex = 14;
            InstallBepinex.Click += InstallBepinex_Click;

            Github.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Right;
            Github.Animated = true;
            Github.BackColor = System.Drawing.Color.Transparent;
            Github.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            Github.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            Github.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            Github.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            Github.FillColor = System.Drawing.Color.Transparent;
            Github.Font = new System.Drawing.Font("Segoe UI", 9F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            Github.ForeColor = System.Drawing.Color.White;
            Github.Image = Properties.Resources.icons8_github_30;
            Github.ImageSize = new System.Drawing.Size(30, 30);
            Github.Location = new System.Drawing.Point(704, 8);
            Github.Name = "Github";
            Github.ShadowDecoration.CustomizableEdges = customizableEdges27;
            Github.ShadowDecoration.Mode = Guna.UI2.WinForms.Enums.ShadowMode.Circle;
            Github.Size = new System.Drawing.Size(35, 35);
            Github.TabIndex = 7;
            Github.Click += Github_Click;

            BrowseTabBtn.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            BrowseTabBtn.Animated = true;
            BrowseTabBtn.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            BrowseTabBtn.BorderRadius = 4;
            BrowseTabBtn.CustomizableEdges = customizableEdges11;
            BrowseTabBtn.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            BrowseTabBtn.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            BrowseTabBtn.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            BrowseTabBtn.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            BrowseTabBtn.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            BrowseTabBtn.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            BrowseTabBtn.ForeColor = System.Drawing.Color.White;
            BrowseTabBtn.HoverState.BorderColor = System.Drawing.Color.FromArgb(35, 35, 35);
            BrowseTabBtn.HoverState.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            BrowseTabBtn.Location = new System.Drawing.Point(14, 14);
            BrowseTabBtn.Name = "BrowseTabBtn";
            BrowseTabBtn.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            BrowseTabBtn.ShadowDecoration.CustomizableEdges = customizableEdges12;
            BrowseTabBtn.Size = new System.Drawing.Size(112, 30);
            BrowseTabBtn.TabIndex = 15;
            BrowseTabBtn.Text = "Browse";
            BrowseTabBtn.Click += BrowseTabBtn_Click;

            InstalledTabBtn.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            InstalledTabBtn.Animated = true;
            InstalledTabBtn.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            InstalledTabBtn.BorderRadius = 4;
            InstalledTabBtn.CustomizableEdges = customizableEdges9;
            InstalledTabBtn.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            InstalledTabBtn.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            InstalledTabBtn.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            InstalledTabBtn.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            InstalledTabBtn.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            InstalledTabBtn.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            InstalledTabBtn.ForeColor = System.Drawing.Color.White;
            InstalledTabBtn.HoverState.BorderColor = System.Drawing.Color.FromArgb(35, 35, 35);
            InstalledTabBtn.HoverState.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            InstalledTabBtn.Location = new System.Drawing.Point(14, 50);
            InstalledTabBtn.Name = "InstalledTabBtn";
            InstalledTabBtn.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            InstalledTabBtn.ShadowDecoration.CustomizableEdges = customizableEdges10;
            InstalledTabBtn.Size = new System.Drawing.Size(112, 30);
            InstalledTabBtn.TabIndex = 16;
            InstalledTabBtn.Text = "Installed";
            InstalledTabBtn.Click += InstalledTabBtn_Click;

            InstalledView.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            InstalledView.BackColor = System.Drawing.Color.FromArgb(33, 33, 33);
            InstalledView.BorderRadius = 5;
            InstalledView.CustomizableEdges = customizableEdges7;
            InstalledView.Location = new System.Drawing.Point(136, 175);
            InstalledView.Name = "InstalledView";
            InstalledView.ShadowDecoration.CustomizableEdges = customizableEdges8;
            InstalledView.Size = new System.Drawing.Size(716, 335);
            InstalledView.TabIndex = 17;
            InstalledView.Visible = false;
            InstalledView.Paint += InstalledView_Paint;

            SettingsView.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left | System.Windows.Forms.AnchorStyles.Right;
            SettingsView.BackColor = System.Drawing.Color.FromArgb(33, 33, 33);
            SettingsView.BorderRadius = 5;
            SettingsView.CustomizableEdges = customizableEdges5;
            SettingsView.Location = new System.Drawing.Point(136, 175);
            SettingsView.Name = "SettingsView";
            SettingsView.ShadowDecoration.CustomizableEdges = customizableEdges6;
            SettingsView.Size = new System.Drawing.Size(716, 335);
            SettingsView.TabIndex = 20;
            SettingsView.Visible = false;
            SettingsView.Paint += SettingsView_Paint;

            LaunchGameBtn.Anchor = System.Windows.Forms.AnchorStyles.Bottom | System.Windows.Forms.AnchorStyles.Left;
            LaunchGameBtn.Animated = true;
            LaunchGameBtn.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            LaunchGameBtn.BorderRadius = 4;
            LaunchGameBtn.CustomizableEdges = customizableEdges3;
            LaunchGameBtn.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            LaunchGameBtn.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            LaunchGameBtn.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            LaunchGameBtn.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            LaunchGameBtn.FillColor = System.Drawing.Color.FromArgb(39, 174, 96);
            LaunchGameBtn.Font = new System.Drawing.Font("Poppins SemiBold", 8.25F, System.Drawing.FontStyle.Bold, System.Drawing.GraphicsUnit.Point);
            LaunchGameBtn.ForeColor = System.Drawing.Color.White;
            LaunchGameBtn.HoverState.BorderColor = System.Drawing.Color.FromArgb(39, 174, 96);
            LaunchGameBtn.HoverState.FillColor = System.Drawing.Color.FromArgb(50, 200, 115);
            LaunchGameBtn.Location = new System.Drawing.Point(14, 480);
            LaunchGameBtn.Name = "LaunchGameBtn";
            LaunchGameBtn.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            LaunchGameBtn.ShadowDecoration.CustomizableEdges = customizableEdges4;
            LaunchGameBtn.Size = new System.Drawing.Size(112, 30);
            LaunchGameBtn.TabIndex = 18;
            LaunchGameBtn.Text = "Launch";
            LaunchGameBtn.Click += LaunchGameBtn_Click;

            SettingsTabBtn.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            SettingsTabBtn.Animated = true;
            SettingsTabBtn.BorderColor = System.Drawing.Color.FromArgb(33, 33, 33);
            SettingsTabBtn.BorderRadius = 4;
            SettingsTabBtn.CustomizableEdges = customizableEdges1;
            SettingsTabBtn.DisabledState.BorderColor = System.Drawing.Color.DarkGray;
            SettingsTabBtn.DisabledState.CustomBorderColor = System.Drawing.Color.DarkGray;
            SettingsTabBtn.DisabledState.FillColor = System.Drawing.Color.FromArgb(169, 169, 169);
            SettingsTabBtn.DisabledState.ForeColor = System.Drawing.Color.FromArgb(141, 141, 141);
            SettingsTabBtn.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            SettingsTabBtn.Font = new System.Drawing.Font("Poppins", 8.25F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point);
            SettingsTabBtn.ForeColor = System.Drawing.Color.White;
            SettingsTabBtn.HoverState.BorderColor = System.Drawing.Color.FromArgb(35, 35, 35);
            SettingsTabBtn.HoverState.FillColor = System.Drawing.Color.FromArgb(21, 21, 21);
            SettingsTabBtn.Location = new System.Drawing.Point(14, 85);
            SettingsTabBtn.Name = "SettingsTabBtn";
            SettingsTabBtn.Padding = new System.Windows.Forms.Padding(0, 2, 0, 0);
            SettingsTabBtn.ShadowDecoration.CustomizableEdges = customizableEdges2;
            SettingsTabBtn.Size = new System.Drawing.Size(112, 30);
            SettingsTabBtn.TabIndex = 19;
            SettingsTabBtn.Text = "Settings";
            SettingsTabBtn.Click += SettingsTabBtn_Click;

            AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            BackColor = System.Drawing.Color.FromArgb(24, 24, 24);
            ClientSize = new System.Drawing.Size(813, 524);
            Controls.Add(SettingsTabBtn);
            Controls.Add(SettingsView);
            Controls.Add(LaunchGameBtn);
            Controls.Add(InstalledView);
            Controls.Add(InstalledTabBtn);
            Controls.Add(BrowseTabBtn);
            Controls.Add(InstallBepinex);
            Controls.Add(ModView);
            Controls.Add(guna2Separator1);
            Controls.Add(FilterDropdown);
            Controls.Add(SearchBox);
            Controls.Add(DashboardBtn);
            Controls.Add(opengamepath);
            Controls.Add(FilePath);
            Controls.Add(undertext);
            Controls.Add(gorillamodmanager);
            Controls.Add(Github);
            Controls.Add(Minimize);
            Controls.Add(Close);
            FormBorderStyle = System.Windows.Forms.FormBorderStyle.None;
            Icon = (System.Drawing.Icon)resources.GetObject("$this.Icon");
            MinimumSize = new System.Drawing.Size(631, 524);
            Name = "MainApp";
            Text = "Gorilla Mod Manager";
            Load += MainApp_Load;
            ResumeLayout(false);
            PerformLayout();
        }

        #region Fields
        private Guna.UI2.WinForms.Guna2BorderlessForm guna2BorderlessForm1;
        private Guna.UI2.WinForms.Guna2AnimateWindow guna2AnimateWindow1;
        private Guna.UI2.WinForms.Guna2Separator guna2Separator1;
        private Guna.UI2.WinForms.Guna2Button opengamepath;
        private Guna.UI2.WinForms.Guna2Button DashboardBtn;
        private Guna.UI2.WinForms.Guna2TextBox FilePath;
        private Guna.UI2.WinForms.Guna2TextBox SearchBox;
        private Guna.UI2.WinForms.Guna2ComboBox FilterDropdown;
        private Guna.UI2.WinForms.Guna2CircleButton Minimize;
        private Guna.UI2.WinForms.Guna2CircleButton Close;
        private Guna.UI2.WinForms.Guna2CircleButton Github;
        private Guna.UI2.WinForms.Guna2Panel ModView;
        private System.Windows.Forms.Label gorillamodmanager;
        private System.Windows.Forms.Label undertext;
        private Guna.UI2.WinForms.Guna2Button InstallBepinex;
        private Guna.UI2.WinForms.Guna2Panel InstalledView;
        private Guna.UI2.WinForms.Guna2Button InstalledTabBtn;
        private Guna.UI2.WinForms.Guna2Button BrowseTabBtn;
        private Guna.UI2.WinForms.Guna2Button LaunchGameBtn;
        private Guna.UI2.WinForms.Guna2Button SettingsTabBtn;
        private Guna.UI2.WinForms.Guna2Panel SettingsView;
        #endregion
    }
}